"""empty message

Revision ID: 3b738b1dda54
Revises: 
Create Date: 2024-05-27 20:25:44.116989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b738b1dda54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('teacher_profile', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_profile', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('lesson_record', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
