"""Added lessons_purchased column

Revision ID: 53667a642fb7
Revises: 3b738b1dda54
Create Date: 2024-05-29 03:23:39.121487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53667a642fb7'
down_revision = '3b738b1dda54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lessons_purchased', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('lessons_purchased')

    # ### end Alembic commands ###
